<a href="https://colab.research.google.com/github/jeyasris2/Cmpe258_HomeWork0/blob/master/Broadcasting_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Broadcasting using numpy**

In [0]:
import numpy as np

**Declaration of array in numpy**

In [0]:
a = np.array([1,2,3],dtype='int')

**Random array generation in numpy**

In [0]:
np.random.seed(0)
a = np.random.rand(3,4)
b = np.random.rand(4)

In [20]:
a

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [21]:
b

array([0.56804456, 0.92559664, 0.07103606, 0.0871293 ])

**Zeros and ones in numpy**

In [16]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
d = np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

**Broadcasting in addition operation**

In [22]:
np.add(a,b)

array([[1.11685807, 1.640786  , 0.67379943, 0.63201248],
       [0.99169936, 1.57149075, 0.50862327, 0.9789023 ],
       [1.53170732, 1.30903816, 0.8627611 , 0.61602422]])

**Broadcasting both the arrays**

In [23]:
d = np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [34]:
e = np.arange(2,11,2)
e

array([ 2,  4,  6,  8, 10])

In [35]:
e = e[:,np.newaxis]
print("shape of e:",e.shape)
e

shape of e: (5, 1)


array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [36]:
d+e

array([[ 3,  5,  7,  9, 11],
       [ 5,  7,  9, 11, 13],
       [ 7,  9, 11, 13, 15],
       [ 9, 11, 13, 15, 17],
       [11, 13, 15, 17, 19]])

**Broadcasting with multiplication example**

In [0]:
g = np.random.rand(2,3)
h = np.random.rand(3)

In [43]:
g*h

array([[0.00933037, 0.64988408, 0.09203604],
       [0.40149265, 0.76384017, 0.09452002]])