Exercises

ƒ * Create a tensor a from list(range(9)). Predict then check what the size, offset, and strides are.

ƒ * Create a tensor b = a.view(3, 3). What is the value of b[1,1]?

ƒ * Create a tensor c = b[1:,1:]. Predict then check what the size, offset, and
strides are.

ƒ * Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch library?

ƒ * Is there a version of your function that operates in-place?

In [0]:
import torch

In [3]:
a_list = list(range(9))
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
a = torch.tensor(a_list)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
b = a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
print(b[1,1])

tensor(4)


In [7]:
c = b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

# Printing Size, stride, offset

In [8]:
c.size()

torch.Size([2, 2])

In [9]:
c.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

In [10]:
c.stride()

(3, 1)

# Cosine and Square root

In [11]:
d = torch.randn(3)
d

tensor([-0.9938,  0.3235, -0.6902])

In [12]:
torch.acos(d)

tensor([3.0303, 1.2413, 2.3325])

In [13]:
torch.sqrt(d)

tensor([   nan, 0.5688,    nan])

# In-place example

In [15]:
d.mul_(2)
d

tensor([-3.9752,  1.2942, -2.7606])